import { Job } from "../typing/job.interface"
import { RapidApiJob } from "../typing/rapidapi.interfaces"

export const getJobs = () => {
    const jobs = {
        "status": "OK",
        "request_id": "2dad9f45-44cd-466e-b584-4498ee56a722",
        "data": [
            {
                "employer_name": "ADEQUAT",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5BSMIt7m2uiId_3142LNElhU-kvf9h48rIEOM&s=0",
                "employer_website": null,
                "job_publisher": "Trabajo.org",
                "job_id": "EymzMi8j8_cAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant Administrative",
                "job_apply_link": "https://fr.trabajo.org/offre-1267-20221230-1d4394dd505476f24fb2273ec6cdee57",
                "job_description": "Poste en CDI à pouvoir dès que possible au Siège d'Adéquat\nNotre service facturation recherche un nouveau talent pour renforcer l'équipe\n\nVos missions :\n• Vérifier la conformité de l'établissement des contrats intérimaires et clients.\n• Transmission d'un mail à l'agence pour traçabilité de la non-conformité du contrat.\n• Saisir informatiquement les bordereaux des clients et intérimaires afin de permettre l'établissement des bulletins de salaire et des auto-factures clients.\n• Relancer les agences pour les bordereaux manquants et le traitement des refus des bordereaux.\n• Prendre en charge l'accueil téléphonique des agences du réseau.\n• Mettre à jour les statistiques et résultats administratifs du service\n• Fournir l'assistance nécessaire aux agences et, de façon générale, promouvoir, à son niveau, un climat relationnel optimum avec les services RH des clients, les agences du réseau et les services supports.\n\nCette liste est non exhaustive et susceptible d'évoluer en fonction des besoins de l'entreprise.\n\nDescription du profil :\n\nProfil :\n• A l'aise avec les chiffres et la gestion administrative.\n• Rigueur et organisation nécessaires.\n• Idéalement première expérience en assistanat ou gestion de la paie et/ou facturation.\n\nRejoignez l'acteur le plus dynamique du secteur depuis 3 ans, et incarnez les valeurs humaines d'Adéquat. Adéquat, simplement pour vous\n\nEntreprise :\n\nDécroche le job Adéquat\n\nAdéquat t'accompagne dans ta recherche d'emploi (intérim, CDD, CDI) et te propose + de 5000 jobs dans tous les secteurs d'activité : Industrie, Logistique, Transport, Bâtiment Travaux Public, Tertiaire\n\nAdéquat c'est + de 260 agences en France et une identité forte : simplicité et proximité\n\nRetrouve toutes nos offres d'emplois sur **************** et candidate facilement avec ou sans CV ou inscris-toi à notre CVthèque pour être visible auprès de nos 1000 recruteurs\n]]>",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672393890,
                "job_posted_at_datetime_utc": "2022-12-30T09:51:30.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=EymzMi8j8_cAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": false,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "KELTIS",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUCntENcslaaKUVySS11M8uAJCtKBKAgaTSSKT&s=0",
                "employer_website": null,
                "job_publisher": "BeBee",
                "job_id": "K1NHuH4aMsEAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Executive Assistant",
                "job_apply_link": "https://fr.bebee.com/job/20221230-c18ffef438ce1e083951d0f8c1f3c439",
                "job_description": "We are looking for an executive assistant in Barcelona for our client.\n\nKey Functions :\n• Writing invitations to meetings and writing emails in a professional level of language\n• Reviewing documents, checking for accuracy and content requirements\n• Take notes during meetings and take minutes of meetings\n• Participate in regular meetings via video conference with managers of different departments in all our clients' companies and facilitate meetings to support clients in their process of compliance with the regulations in force.\n• Maintain records, prepare audit questionnaires\n• Compile relevant information, prepare summary reports, and create statistics\n• Transferring databases from Excel spreadsheets to company software\n• Monitor performance indicators and produce regular reports of risk assessments\nDescription du profil :\n\nAt least three years of experience as an executive assistant, knowledge of law and data protection regulations is better\n\nStrong written and verbal communication skills, Ability to multi-task, Cross-cultural knowledge in dealing with international clients\n\nOrganised, goal-oriented and positive attitude. Team spirit and motivation\n\nBe able to adapt to complex communication situations and be comfortable in discussions with executives of multinational companies\n\nEntreprise :\n\nKELTIS est un cabinet spécialisé dans les domaines Transport & Logistique, Ingénierie Technique, Informatique & Télécommunication et Métiers supports.\nDans un contexte de mutation profonde du marché du travail, notre ambition est de mettre à profit nos expertises et nos compétences pour accompagner les décideurs dans la mise en place de leurs politiques de recrutement.\nNotre objectif : accompagner les entreprises dans le recrutement de leurs collaborateurs qui réaliseront leurs projets de demain.",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672427740,
                "job_posted_at_datetime_utc": "2022-12-30T19:15:40.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=K1NHuH4aMsEAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-07T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1673049600,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": 36,
                    "experience_mentioned": true,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "3C EXPERTISES",
                "employer_logo": null,
                "employer_website": null,
                "job_publisher": "BeBee",
                "job_id": "27FKvP7JjWQAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant formation H/F",
                "job_apply_link": "https://fr.bebee.com/job/20221230-f338b053f85aa16a895aa54da41d87b8",
                "job_description": "Au sein de la Direction Expertise à Distance de la Société 3C Expertises (Groupe ADENES), nous recherchons pour notre bureau de Lyon (3eme) un Assistant formation H/F.\nRattaché à la Responsable Formation, vous organisez, gérez et coordonnez les actions de formation mises en oeuvre au sein du Groupe. A ce titre, vous êtes en charge de :\nPlanifier, Organiser et veiller à la gestion logistique des actions de formation en liaison avec les formateurs et intervenants :\nPlanification des actions de formation selon les disponibilités des formateurs\nActualisation du catalogue de formation sur les outils et publication utilisées\nRéservation des salles de formation en lien avec les services Moyens généraux / Achats du groupe\nSuivi des relations avec les différents partenaires\nLa gestion administrative de la formation :\nSuivi du planning des formations et de la réalisation des évaluations avec relance en cas de non réalisation ou de retard, alerte en cas d'absence de formateurs, indisponibilité des salle de formation ou de matériel) et suivi de la résolution de l'incident.\nRéservation et vérification de la disponibilité des différents moyens nécessaires (salle, matériel, logiciel, documents ...).\nProduction, vérification et édition des différents documents des documents liés aux prestations de formation (inscriptions, conventions de formation, convocations, feuilles de présence attestations de formation, questionnaires).\nParticipation à la rédaction des revues de presse\nParticipation à la réflexion et au déploiement d'outils numériques novateurs à destination de la formatio\n\nDescription du profil :\n\nTitulaire d'un Bac +2/3 Assistant formation ou de Direction et vous avez de bonnes connaissances du secteur de la formation.\nVous justifiez d'une expérience significative de 3 ans minimum au sein d'un service formation.\nVous bénéficiez d'une expérience en gestion, saisie et organisation de données. Vous avez déjà mis à jour des bases de données et maîtrisez les extractions. Vous maitrisez donc parfaitement le pack office.Vous êtes reconnu pour la qualité de vos saisies de données et de vos mises en page de documents.\n\nVous êtes rigoureux, très organisé et vous appréciez de gérer les priorités et d'alterner entre différentes activités.\nPolyvalent, vous êtes capable de passer rapidement d'une activité à l'autre tout en respectant les échéances qui vous ont été fixées.\n\nAvenant et ayant le sens du contact, vous aimez informer, communiquer avec le sourire et savez adapter votre discours à votre interlocuteur.\n\nAu-delà de vos compétences métiers, vos qualités humaines seront vos atouts : Réactif et curieux, vous êtes force de propositions afin d'apporter une réelle valeur ajoutée dans votre travail.\nREJOIGNEZ NOUS\n\nLe Groupe ADENES et sa filiale 3C sont engagés en faveur de l'égalité des chances pour les travailleurs en situation de handicap.\n\nRémunération annuelle selon profil et expérience de 24 000EUR à 28 000EUR annuels selon profil et expériences (sur 13 mois).\nVous bénéficierez d'une carte tickets restaurant, de la mutuelle employeur.REJOIGNEZ NOUS\nLe Groupe ADENES et sa filiale 3C sont engagés en faveur de l'égalité des chances pour les travaille\n\nEntreprise :\n\n3C filiale du groupe Adenes est né du regroupement de cabinets d'expertise technique spécialisés dans le domaine de la construction et répartis sur le territoire national.\n\nComposé d'hommes et de femmes de terrain, ingénieurs, architectes et techniciens bâtiment, notre équipe est animée d'une volonté de servir les assureurs confrontés aux sinistres construction avec compétence et efficacité.\n\nNos 170 collaborateurs défendent chaque jour nos valeurs : respect, honnêteté intellectuelle, efficacité, écoute et compétence technique.\n\nAttentifs aux souhaits spécifiques, nous assurons une prestation optimale à toutes les étapes de l'expertise et ceci dans la maîtrise des coûts et des délais.\n\n3C est membre du Groupe ADENES, leader de l'expertise en France sur plusieurs segments de marché.",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672382687,
                "job_posted_at_datetime_utc": "2022-12-30T06:44:47.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=27FKvP7JjWQAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-07T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1673049600,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": 36,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "EXPERTIVE",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5BSMIt7m2uiId_3142LNElhU-kvf9h48rIEOM&s=0",
                "employer_website": null,
                "job_publisher": "Trabajo.org",
                "job_id": "39SD-i7vIywAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "(H/F) Assistant(e) Administratif(ve) – Italien – Lyon 2 – CDI –",
                "job_apply_link": "https://fr.trabajo.org/offre-861-20221230-a59b6cb3f3380c9466fa28d42e7ede1f",
                "job_description": "(H/F) Assistant(e) Administratif(ve) – Italien – Lyon 2 – CDI –\nCDI Lyon - 2ème arrondissement Auvergne-Rhône-Alpes - Rhône - Auvergne-Rhône-Alpes TEAMEXPERT - Pôle Tertiaire\nTeam expert, cabinet de recrutement à taille humaine vous accompagne pour donner un nouvel envol à votre carrière. Afin de mieux répondre à vos enjeux, tous nos consultants sont spécialisés par secteur d'activité. Nous établissons avec nos clients et nos candidat(e)s un véritable partenariat triangulaire, fondé sur l'écoute et l'expertise, afin de réussir ensemble un recrutement optimal.\n\nLe poste\nTeam expert, cabinet de recrutement, recherche pour un de ses clients:\nUn(e) Assistant(e) Administratif(ve) - Italien - Lyon 2 - CDI -\n\nAu sein d'un cabinet dont le management est sympathique et bienveillant, vos principales missions seront:\n\n- Accueil physique et téléphonique:\n- Très peu d'appels, les salariés travaillent et communiquent avec leur portable PRO.\n- Peu d'accueil physique (beaucoup d'échanges par mail, téléphone, Visio). Préparer les salles de réunions, veiller au bien être des visiteurs (café...).\n\n- Gestion administrative des dossiers clients : Ouverture, suivi, ajout de documents...\n\n- Transmission de documents.\n\n- Mise en forme et frappe de documents.\n\n- Numérisation, archivage.\n\n- Classement de dossiers.\n\nVos missions peuvent bien entendu se diversifier en fonction de l'agenda de votre équipe (congés...).\n\nVotre profil\n- Bac + 2: BTS Gestion PME- PMI, SAM, MCO, assistant manager ou équivalent.\n\n- Vous parlez l'italien (langue de travail).\n- Vous maîtrisez le Word (mise en forme de dossiers) Powerpoint (Présentation de contenus sur le site).\n- La frappe sous audio est 1+\n- Vous aimez travailler dans un bon esprit d'équipe tout en autonomie.\n- Votre excellent relationnel et orthographe en français seront des atouts de réussite pour ce poste\n- Vous êtes intéressé(e) pour intégrer un cabinet d'avocats\n\nEnvoyez-moi votre CV\n\nLes avantages:\n- CDI\n- Lyon 2\n- Temps partiel\n- Salaire : A partir de KEUR selon profil\n- TR 9, EUR\n- Prise de poste : Dès que possible.\n\nL'entreprise a des process de travail bien précis, qui ont fait leur preuve Ils veulent recruter une personne qui s'aura s'adapter, se les approprier, intégrer cette super équipe\n\nDes bases en Italien sont indispensables car ils veulent un (e) collègue qui se sente bien parmi eux\nPublié il y a 3 heures Postuler Retour Toutes les offres de TEAMEXPERT - Pôle Tertiaire Contacter nos agences",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672375120,
                "job_posted_at_datetime_utc": "2022-12-30T04:38:40.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=39SD-i7vIywAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "ADEQUAT",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJQWuKcSBGJkh_w3bVBdqXkLDryHHTifStK_xK&s=0",
                "employer_website": null,
                "job_publisher": "BeBee",
                "job_id": "BVScl9MIv1oAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant administratif",
                "job_apply_link": "https://fr.bebee.com/job/20221229-44e3e0c7d31ee7ddf5a52cb37346b7cb",
                "job_description": "ADEQUAT\nNotre Pôle Services Généraux situé au Siège recherche un nouveau talent pour renforcer ses équipes : un Assistant Administratif (H/F) Vos missions :\n\n- Assurer l'interface entre la Direction Achats, les agences, les fournisseurs et les prospects.\n- Assurer l'accueil téléphonique et physique des collaborateurs du réseau, des fournisseurs et prospects.\n- Gestion de la flotte automobile (assurances, commandes, contrats).\n- Gestion des fournitures et suivi des locaux.\n- Réaliser les devis émis par les collaborateurs des agences et du siège.\n- Établir les tableaux de synthèse et traiter les différents courriers du service.\nParce que nous attendons de vous d'être :\n\nSimples : ouverture d'esprit, transparence des relations, proximité clients/candidats/collaborateurs, humilité Prise en compte et respect des personnes : écoute active, coopération, esprit d'équipe, respect des individualités, confiance Sens du service, respect de la confidentialité.\nVotre savoir-être :\n\nRigueur, réactivité, sens de la communication, capacité d'analyse et de synthèse. Rôle de conseil et pédagogie.\n\nRejoignez l'acteur le plus dynamique du secteur depuis 3 ans, et incarnez les valeurs humaines d'Adéquat. Adéquat, simplement pour vous",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672289808,
                "job_posted_at_datetime_utc": "2022-12-29T04:56:48.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=BVScl9MIv1oAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": false,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "Manpower CDICDD",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5BSMIt7m2uiId_3142LNElhU-kvf9h48rIEOM&s=0",
                "employer_website": null,
                "job_publisher": "Trabajo.org",
                "job_id": "ojLuMeBBLkEAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant de direction",
                "job_apply_link": "https://fr.trabajo.org/offre-1267-20221230-5a9ba0dcce022865291130b802d5aab7",
                "job_description": "Manpower CABINET DE RECRUTEMENT LYON SPECIALISE recherche pour son client, un acteur du secteur de la santé, un Assistant de direction (H/F)\nRattaché(e) à la direction Générale, vous êtes en charge de son assistanat, de la communication de la Fondation et du suivi en direct de certains projets: REDACTION - ORGANISATION -SYNTHESE\n• Gestion des instances: préparation des convocations au conseil d'administration et Comité de Direction, des documents nécessaires à leur teue, participation aux réunions\n• Rrédaction des comptes-rendus CODIR er Conseil d'administration\n• Appui à la realisation et au suivide projets en lien avec la Direction Générale\n• Accueil physique et téléphonique des differents interlocuteurs de le direction\n• Gestion de l'agenda, organisation des rendez-vous et preparation de reunions\n• Elabration d'outils de pilotage pour venir en aide du pôle RH et finance.\n• Traitement du courrier, courriels et rédaction/production de documents\n• Redaction de publication de post sur els reseaux sociaux\n• Gestion avec les prestatiares externes web\n• Redaction d'un journal interne\n• Organisaton d'évènements\n\nTitulaire d'un BAC +2 minimum avec au moins 3 années d'expérience, vous souhaitez vous investir auprès d'un groupe d'utilité publique.Alors j'ai sans doute le poste qu'il vous faut.\n\nPour reussir sur ce poste il faut:\n• D'excellentes capacités rédactionnelles. Bien sur zéro faute d'orthographe, aimer rediger et synthetiser seront vos atout pour exceller sur ce poste.\n• Une grande rigueur et une bonne dose d'organisation\n• Une bonne gestion des priorités\n• Etre autonome tout en ayant une bonne aisance relationnelle\n• Vous saurez anticiper les besoins de la Direction Générale\n• Avoir une première experience en animation de réseaux sociaux\n\n?Vous vous reconnaissez? Alors postulez\n\nDans le cadre de sa politique diversité, Manpower étudie, à compétences égales, toutes candidatures dont celles de personnes en situation de handicap\n\nEntreprise :\n\nCette offre d'emploi est publiée par Manpower (créateur de solutions pour l'emploi tous types de contrat CDI, CDD et Interim) pour le compte d'un de ses clients.\n]]>",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672391571,
                "job_posted_at_datetime_utc": "2022-12-30T09:12:51.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=ojLuMeBBLkEAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": 36,
                    "experience_mentioned": true,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "ATOLL GROUPE",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU-w78VViGwQ0eXzH_FMgGp9bxv_w9RkRpW5R8&s=0",
                "employer_website": null,
                "job_publisher": "BeBee",
                "job_id": "u8bK9QdIxmcAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant administratif",
                "job_apply_link": "https://fr.bebee.com/job/20221229-343783ae02b553a6048ca8f553581613",
                "job_description": "Alp Emploi recrute pour son client, un laboratoire spécialisé dans les tests de sécurité sur les biens de consommation destinés au grand public et les produits industriels, un Assistant Administratif (h/f).Poste: CDD ou intérim en vue d'embauche à pourvoir pour Mi-JanvierLieu: Lyon 7ème Salaire: 1800 à 2000 euros brut / mois Temps de travail: 35hRédaction de rapport d'essai pour les clients Réception des colis / échantillons Archivage des factures Achat de billets de trains pour les commerciaux, achats divers administratifsRemplacement au standard (de manière ponctuelle).Liste non exhaustiveVous êtes de nature curieux, vous êtes quelqu'un de polyvalent et dynamique.Vous êtes autonome Vous maîtrisez le pack office Vous êtes reconnu pour votre excellente orthographe",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672327276,
                "job_posted_at_datetime_utc": "2022-12-29T15:21:16.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=u8bK9QdIxmcAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": false,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "HCL SIEGE ADMINISTRATIF",
                "employer_logo": null,
                "employer_website": null,
                "job_publisher": "Pôle Emploi",
                "job_id": "OUaHmg7Iam0AAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant administratif / Assistante administrative (H/F)",
                "job_apply_link": "https://candidat.pole-emploi.fr/offres/recherche/detail/145XLSN",
                "job_description": "Missions principales :\nLe poste comporte 3 ensembles de missions :\n1. L'agent assure la gestion administrative du Département Architecture et Maîtrise d'Œuvre :\n- secrétariat courant (accueil téléphonique, gestion des agendas et du courrier, frappe de courrier, programmation et organisation matérielle de réunions, frappe de courriers, reprographie et diffusion, classement archivage des dossiers)\n- assistance administrative (rédaction de courrier, compte rendu de réunions, et documents divers, création ou mise en forme de présentations, analyse des offres de certaines prestations intellectuelles)\n- gestion administrative (dossiers techniques, états d'heures, déplacements, approvisionnements en fourniture)\n2. L'agent assure la commande, la gestion, l'attribution et l'échange des équipements de téléphonie portable sous la responsabilité et en collaboration avec l'ingénieur du département de maintenance et exploitation.\n3. L'agent assure des missions de soutien au cadre administratif chargé des ressources humaines et des affaires générales.\n\nQualifications :\nDiplôme BAC à BAC+2\n\nCompétences :\nConnaissances approfondies des logiciels bureautiques : Word, Excel, Power Point, Outlook\nConnaissance des acteurs à l'acte de construire et de la mission de conduite d'opération est un plus\n\nSavoir-être :\nSens du travail en équipe\nCapacité d'analyse et réactivité\nCapacité à rendre compte rapidement\nRigueur et discrétion\n\nConditions d'embauche :\nPoste à temps plein et à repos fixe 7h30 par jour soit 37h 30 hebdomadaire (15RTT par an)\nLes congés annuels sont organisés, en lien avec le/la cadre de l'unité, de manière à assurer la permanence et la continuité du service. Le poste s'intègre dans une organisation globale des secrétariats rue Villon incluant des contraintes notamment de coordination des périodes de congés et d'intérim.",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672272000,
                "job_posted_at_datetime_utc": "2022-12-29T00:00:00.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=OUaHmg7Iam0AAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-12-29T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1703808000,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": [
                    "Réaliser la gestion administrative du courrier"
                ],
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": 2160,
                "job_max_salary": 2160,
                "job_salary_currency": "EUR",
                "job_salary_period": "MONTH",
                "job_highlights": {}
            },
            {
                "employer_name": "Manpower Intérim",
                "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRviIOqbxeOx6Nfrit07ZJmgnjlgM9CtDQYzGTb&s=0",
                "employer_website": null,
                "job_publisher": "BeBee",
                "job_id": "1APHzAvUMrwAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant administratif",
                "job_apply_link": "https://fr.bebee.com/job/20221229-56133d11d58f081ee1869bc3c925c71c",
                "job_description": "Entreprise :Cette offre d'emploi est publiée par Manpower (créateur de solutions pour l'emploi tous types de contrat CDI, CDD et Interim) pour le compte d'un de ses clients.Description du poste :Manpower LYON TERTIAIRE recherche pour son client, un acteur du secteur culturel, un Assistant administratif et comptable (H/F) - Assurer la collecte des factures fournisseurs, établir une facturation clients et suivi des règlements- Assurer le suivi financier des dossier immobiliers (assurances, sinistres, cession...)- Participer à l'élaboration des outils de gestion de la Fondation : budget prévisionnel, plan de trésorerie- Assurer la gestion et le suivi de la trésorerie- Participer à l'élaboration pour chaque manifestation culturelle d'un budget prévisionnel spécifique- Elaborer les dossiers de demande de subvention préparés avec l'équipe de la Fondation et en assurer la perception- .... Niveau bac +2 Expérience souhaitéMaîtrise des logiciels Pack Office et Indesign ainsi que des réseaux sociaux Dans le cadre de sa politique diversité, Manpower étudie, à compétences égales, toutes candidatures dont celles de personnes en situation de handicap",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672356473,
                "job_posted_at_datetime_utc": "2022-12-29T23:27:53.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=1APHzAvUMrwAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            },
            {
                "employer_name": "Eurofins",
                "employer_logo": "https://cdnmedia.eurofins.com/eurofins-germany/media/2160/logo.png",
                "employer_website": "http://www.eurofins.com",
                "job_publisher": "Trabajo.org",
                "job_id": "elJWmKU-78cAAAAAAAAAAA==",
                "job_employment_type": "FULLTIME",
                "job_title": "Assistant(e) achats",
                "job_apply_link": "https://fr.trabajo.org/offre-861-20221230-3f921ad8ded1a8461e72714d88236abf",
                "job_description": "Description de l'entreprise\n\nEurofins Scientific est une entreprise internationale spécialisée dans les sciences de la vie qui propose une gamme unique de services de tests analytiques à ses clients dans de nombreux secteurs afin de rendre la vie et notre environnement plus sûrs, plus sains et plus durables. De la nourriture que vous mangez, à l’eau que vous buvez, aux médicaments sur lesquels vous comptez, Eurofins travaille avec les plus grandes entreprises du monde pour s’assurer que les produits fournis soient sûrs, que leurs ingrédients soient authentiques et que l’étiquetage soit exact. Eurofins se positionne comme le leader mondial de l’analyse des produits alimentaires, pharmaceutiques, environnementaux, cosmétiques et des services de recherche contractuelle (CRO) en agrosciences. C'est également l'un des leaders mondiaux indépendants sur le secteur de certains services de tests et de laboratoires dans le domaine de la génomique, de la découverte pharmacologique, des analyses médico-légales, du CDMO (Contract Development & Manufacturing Organisation), des sciences avancées des matériaux ainsi qu'en support aux études cliniques.\n\nEn 30 ans, Eurofins a évolué d'un laboratoire unique à Nantes, en France, à plus de 58. employés répartis sur un réseau de plus de entreprises indépendantes dans plus de 54 pays et exploitant plus de laboratoires. Eurofins offre un portefeuille de plus de . méthodes d'analyse pour évaluer la sécurité, l'identité, la composition, l'authenticité, l'origine, la traçabilité et la pureté de substances et de produits biologiques, ainsi que pour fournir des services de diagnostic clinique innovants en tant qu'un des principaux acteurs émergents au niveau mondial dans le domaine des tests de diagnostics cliniques spécialisés.\n\nEn , Eurofins a réalisé un chiffre d'affaires total de 5,4 milliards d'euros et a été l'une des actions les plus performantes en Europe au cours des 20 dernières années.\n\nDescription du poste\n\nL’Assistant(e) Achats au Central Procurement a comme missions principales :\n\n- l'animation des bases de données achats dans nos ERP (créations et mises à jour articles, fournisseurs)\n\n- la gestion des demandes internes émanant des utilisateurs\n\n- l’actualisation des informations disponibles via notre extranet achats\n\n- l’extraction des reportings achats et de la mise à jour de leur paramétrage\n\n- le contrôle des factures fournisseurs et du reporting des déviations de process\n\n- le support au déploiement de notre ERP achats\n\n- le support aux acheteurs dans leur démarche de déploiement, collecte des données, préparation aux business review meetings avec les fournisseurs\n\n- la participation à notre démarche de standardisation article et de rationalisation fournisseur\n\n- la gestion de certaines négociations (classe C)\n\n- la participation à l’édition des Newsletters\n\n- la mise à jour de nos bases de données (RFA, IFRS16, Contrats…)\n\nCes missions pourront être amenées à évoluer dans le temps selon les besoins de la société.\n\nQualifications\n\nL’Assistant(e) Achats au Central Procurement de Lyon maîtrisera les compétences suivantes :\n\n- l’utilisation d’un ou plusieurs ERP\n\n- l'excellente connaissance du flux de commande à la facturation\n\n- la connaissance des contraintes métiers\n\n- la maîtrise des outils du pack office\n\n- l’anglais\n\nInformations complémentaires\n\nDépend de : Purchasing Team Leader - Clinical Diagnostics\n\nA une fonction d'encadrement : non\n\nPérimètre couvert : France\n\nContrat : CDI\n\nDate de démarrage : au plus vite",
                "job_is_remote": false,
                "job_posted_at_timestamp": 1672371845,
                "job_posted_at_datetime_utc": "2022-12-30T03:44:05.000Z",
                "job_city": "Lyon",
                "job_state": null,
                "job_country": "FR",
                "job_latitude": 45.76404,
                "job_longitude": 4.835659,
                "job_benefits": null,
                "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=assistant+lyon,+fr&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=assistant+lyon,+fr&htidocid=elJWmKU-78cAAAAAAAAAAA%3D%3D",
                "job_offer_expiration_datetime_utc": "2023-01-06T00:00:00.000Z",
                "job_offer_expiration_timestamp": 1672963200,
                "job_required_experience": {
                    "no_experience_required": false,
                    "required_experience_in_months": null,
                    "experience_mentioned": false,
                    "experience_preferred": false
                },
                "job_required_skills": null,
                "job_required_education": {
                    "postgraduate_degree": false,
                    "professional_certification": false,
                    "high_school": false,
                    "associates_degree": false,
                    "bachelors_degree": false,
                    "degree_mentioned": true,
                    "degree_preferred": false,
                    "professional_certification_mentioned": false
                },
                "job_experience_in_place_of_education": false,
                "job_min_salary": null,
                "job_max_salary": null,
                "job_salary_currency": null,
                "job_salary_period": null,
                "job_highlights": {}
            }
        ]

    }
    return rapidApiJobToJob(jobs.data);
}

export const rapidApiJobToJob = (rapidApiJobs: RapidApiJob[]) => {
    return (
        rapidApiJobs.map(job => {
            return {
                id: job.job_id,
                intitule: job.job_title,
                description: job.job_description,
                dateCreation: job.job_posted_at_datetime_utc,
                lieuTravail: {
                    libelle: job.job_city,
                    latitude: job.job_latitude,
                    longitude: job.job_longitude,
                    commune: job.job_city
                },
                entreprise: {
                    nom: job.employer_name,
                    logo: job.employer_logo,
                    url: job.employer_website
                },
                typeContrat: job.job_employment_type,
                salaire: {
                    libelle: job.job_max_salary ?? job.job_min_salary,
                },
                contact: {
                    urlRecruteur: job.job_apply_link,
                    urlPostulation: job.job_apply_link
                },
                origineOffre: {
                    origine: job.job_publisher,
                    urlOrigine: job.job_apply_link,
                }
            }
        })
    )
}